# Generated by Django 4.2.4 on 2023-08-12 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_customuser_phone_number_customuser_pic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='partners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
