# Generated by Django 4.2.4 on 2023-08-12 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0006_delete_categorysharerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_received_share_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sent_share_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
