# Generated by Django 4.2.4 on 2023-08-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exact_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeating',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('not repeated', 'Not repeated')], default='daily', max_length=30),
        ),
    ]
