# Generated by Django 4.2.4 on 2023-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_exact_day_alter_task_repeating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='task',
            name='interval_option',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='interval_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeating',
            field=models.CharField(choices=[('repeated', 'Repeated'), ('not repeated', 'Not repeated')], default='repeated', max_length=30),
        ),
    ]
