# Generated by Django 4.2.4 on 2023-08-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_sharedwith_task_shared_with_tasksharerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksharerequest',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=15),
        ),
    ]
