# Generated by Django 4.2.4 on 2023-08-12 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_remove_task_category_task_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='who_has_to_make',
            field=models.ManyToManyField(blank=True, related_name='duties', to=settings.AUTH_USER_MODEL),
        ),
    ]
