# Generated by Django 4.2.4 on 2023-08-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
