# Generated by Django 4.2.4 on 2023-08-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_rename_subtitle_onboarding_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='image',
            field=models.ImageField(upload_to='boarding_images/'),
        ),
    ]
